volumes:
  grafana_data:

networks:
  front-tier:
  back-tier:

include:
  # - alertmanager/compose.yml
  - cadvisor/compose.yml
  - loki/compose.yml
  - mimir/compose.yml
  - mimir/load-balancer/compose.yml
  - mimir/minio/compose.yml
  # - node-exporter/compose.yml
  - prometheus/compose.yml
  - promtail/compose.yml

services:

  grafana:
    image: grafana/grafana:latest
    user: "472"
    depends_on:
      - mimir-1
      - mimir-2
      - mimir-3
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always