volumes:
  minio-data:

networks:
  back-tier:

services:  
  minio-tempo:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-euc", "mkdir -p /data/tempo && minio server /data --console-address ':9001'"]
    environment:
      - MINIO_ROOT_USER=tempo
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data
    ports:
      - 9001:9001
    networks:
      - back-tier