networks:
  back-tier:

services:  
  windows-exporter:
    image: prometheuscommunity/windows-exporter:latest
    ports:
      - 9182:9182
    volumes:
      - ./:/etc/windows-exporter/
      - ./config.yml/:/etc/windows-exporter/config.yml
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/windows-exporter/config.yml'
      - '--storage.path=/windows-exporter'