volumes:
  prometheus_data:

networks:
  back-tier:

services:  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./:/etc/prometheus/
      - prometheus_data:/prometheus
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=error"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      # - alertmanager:alertmanager
    #      - pushgateway:pushgateway
    # depends_on:
      # - cadvisor
      # - mimir-1
      # - mimir-2
      # - mimir-3
    #      - pushgateway
    networks:
      - back-tier
    restart: always

  #    deploy:
  #      placement:
  #        constraints:
  #          - node.hostname == ${HOSTNAME}