# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:

- name: Loki
  # <string, required> datasource type. Required
  type: loki
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://loki:3100
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  # <string> database name, if used
  database:
  # <bool> enable/disable basic auth
  basicAuth: false
  # <string> basic auth username, if used
  basicAuthUser:
  # <string> basic auth password, if used
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault: false
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
- name: Mimir
  type: prometheus
  access: proxy
  orgId: 1
  url: http://load-balancer:9009/prometheus
  version: 1
  editable: true
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
    alertmanagerUid: "alertmanager"
  secureJsonData:
    httpHeaderValue1: "o11y"
  isDefault: true
- name: Mimir Alertmanager
  uid: alertmanager
  type: alertmanager
  access: proxy
  orgId: 1
  url: http://load-balancer:9009/
  version: 1
  editable: true
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
    implementation: "cortex"
  secureJsonData:
    httpHeaderValue1: "o11y"