networks:
  back-tier:
  front-tier:

services:
  mimir-load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mimir-1
      - mimir-2
      - mimir-3
    ports:
      - 9009:9009
    restart: always
    networks:
      - back-tier
      - front-tier