volumes:
  minio-data:

networks:
  back-tier:

services:  
  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-euc", "mkdir -p /data/mimir /data/tempo && minio server --quiet /data"]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
    networks:
      - back-tier