networks:
  back-tier:

services:  
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./:/etc/promtail/
      - ./config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - back-tier