server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - docker:
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          monitor: "ops-qa"
          server: "alphacentauri"
          platform: "o11y"
          __path__: /var/log/*.log

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      listen_protocol: tcp
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
        monitor: "ops-qa"
        server: "alphacentauri"
        platform: "o11y"
    relabel_configs:
      - source_labels: ["__syslog_message_hostname"]
        target_label: "host"

  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      matches: _TRANSPORT=kernel
      labels:
        job: systemd-journal
        monitor: "ops-qa"
        server: "alphacentauri"
        platform: "o11y"
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"

  - job_name: systemd-journal
    journal:
      labels:
        job: default/systemd-journal
        monitor: "ops-qa"
        server: "alphacentauri"
        platform: "o11y"
      path: /var/log/journal
    relabel_configs:
      - source_labels:
          - __journal__systemd_unit
        target_label: systemd_unit
      - source_labels:
          - __journal__hostname
        target_label: nodename
      - source_labels:
          - __journal_syslog_identifier
        target_label: syslog_identifier
