networks:
  back-tier:
  front-tier:

services:
  distributor:
    image: &tempoImage grafana/tempo:latest
    command: "-target=distributor -config.file=/etc/tempo/config.yml"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  ingester-0:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo/config.yml"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  ingester-1:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo/config.yml"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  ingester-2:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo/config.yml"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  query-frontend:
    image: *tempoImage
    command: "-target=query-frontend -config.file=/etc/tempo/config.yml -log.level=debug"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200:3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  querier:
    image: *tempoImage
    command: "-target=querier -config.file=/etc/tempo/config.yml -log.level=debug"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  compactor:
    image: *tempoImage
    command: "-target=compactor -config.file=/etc/tempo/config.yml"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  metrics-generator:
    image: *tempoImage
    command: "-target=metrics-generator -config.file=/etc/tempo/config.yml"
    restart: always
    volumes:
      - ./config.yml:/etc/tempo/config.yml
    ports:
      - "3200"   
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      
