server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"

ingester:
  max_block_duration: 15m

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - ingester-0:7946
  - ingester-1:7946
  - ingester-2:7946
  - metrics-generator-0:7946
  - metrics-generator-1:7946

compactor:
  compaction:
    block_retention: 336h

querier:
  frontend_worker:
    frontend_address: query-frontend:9095

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: 
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9009/api/v1/push
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: minio:9000
      access_key: mimir
      secret_key: supersecret
      insecure: true                     # backend configuration to use
    wal:
      path: /var/tempo/wal             # where to store the wal locally
    local:
      path: /var/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] 
      generate_native_histograms: both